version: '3.3'

services:
  W3Bot:
    image: 'henryxiaoyang/w3bot:latest'
    restart: unless-stopped
    container_name: 'W3Bot'
    environment:
      WC_AUTO_RESTART: 'yes'
    ports:
      - '4000:8080'
    extra_hosts:
      - 'dldir1.qq.com:127.0.0.1'
    volumes:
      - 'W3Bot:/home/app/W3Bot/'
      - 'W3Bot-wechatfiles:/home/app/WeChat Files/'
    tty: true

volumes:
  W3Bot:
  W3Bot-wechatfiles:
